# Generated by Django 5.0.4 on 2024-05-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_products_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
